#!/usr/bin/env php
<?php

use Tempest\Console\ConsoleApplication;
use Tempest\Core\DiscoveryLocation;

require_once getcwd() . '/vendor/autoload.php';

ConsoleApplication::boot(
    discoveryLocations: [
        new DiscoveryLocation('Tests\\Tempest\\Fixtures\\', __DIR__ . '/tests/Fixtures')
    ],
)->run();

exit;