#!/usr/bin/env php
<?php

use Tempest\Console\ConsoleApplication;
use Tempest\AppConfig;
use Tempest\Discovery\DiscoveryLocation;use Tempest\Environment;

require_once getcwd() . '/vendor/autoload.php';

ConsoleApplication::boot(
    'Tempest Console',
    new AppConfig(
        root: getcwd(),
//        environment: Environment::PRODUCTION,
        enableExceptionHandling: true,
        discoveryCache: false,
        discoveryLocations: [
            new DiscoveryLocation('Tests\\Tempest\\Fixtures', __DIR__ . '/tests/Fixtures'),
        ],
    ),
)->run();