<?php

declare(strict_types=1);

namespace Tempest\Generation\TypeScript\Writers;

use Tempest\Generation\TypeScript\InterfaceDefinition;
use Tempest\Generation\TypeScript\TypeDefinition;
use Tempest\Generation\TypeScript\TypeNodeRenderer;
use Tempest\Generation\TypeScript\TypeScriptOutput;
use Tempest\Generation\TypeScript\TypeScriptWriter;
use Tempest\Support\Arr;
use Tempest\Support\Filesystem;
use Tempest\Support\Str;

/**
 * Writes TypeScript definitions to separate .ts files organized by namespace in a directory structure.
 */
final class DirectoryWriter implements TypeScriptWriter
{
    private TypeNodeRenderer $renderer {
        get => $this->renderer ??= new TypeNodeRenderer();
    }

    public function __construct(
        private readonly DirectoryTypeScriptGenerationConfig $config,
    ) {}

    public function write(TypeScriptOutput $output): void
    {
        Filesystem\ensure_directory_exists($this->config->directory);
        Filesystem\ensure_directory_empty($this->config->directory);

        $fileGroups = [];

        foreach ($output->namespaces as $namespace => $definitions) {
            $filename = $this->namespaceToFilePath($namespace);

            $fileGroups[$filename] ??= [];
            $fileGroups[$filename][$namespace] = $definitions;
        }

        foreach ($fileGroups as $filename => $namespaces) {
            Filesystem\write_file(
                filename: $filename,
                content: $this->generateFileContent($namespaces),
            );
        }
    }

    /**
     * @param array<string, array<TypeDefinition|InterfaceDefinition>> $namespaces
     */
    private function generateFileContent(array $namespaces): string
    {
        $lines = [];
        $lines[] = '/*';
        $lines[] = '|----------------------------------------------------------------';
        $lines[] = '| This file contains TypeScript definitions generated by Tempest.';
        $lines[] = '|----------------------------------------------------------------';
        $lines[] = '*/';
        $lines[] = '';

        $imports = $this->collectImports($namespaces);

        if ($imports !== []) {
            foreach ($imports as $import) {
                $lines[] = $import;
            }

            $lines[] = '';
        }

        foreach ($namespaces as $definitions) {
            foreach ($definitions as $definition) {
                $lines[] = $this->generateDefinition($definition);
                $lines[] = '';
            }
        }

        return (string) Arr\implode($lines, glue: "\n");
    }

    /**
     * @param array<string,array<TypeDefinition|InterfaceDefinition>> $namespaces
     * @return array<string>
     */
    private function collectImports(array $namespaces): array
    {
        $imports = [];
        $currentNamespaces = array_keys($namespaces);

        foreach ($namespaces as $namespace => $definitions) {
            foreach ($definitions as $definition) {
                $references = $definition instanceof TypeDefinition
                    ? $definition->type->references
                    : $this->collectInterfaceReferences($definition);

                foreach ($references as $fqcn) {
                    $targetNamespace = Str\before_last($fqcn, '\\');

                    if (in_array($targetNamespace, $currentNamespaces, strict: true)) {
                        continue;
                    }

                    $typeName = Str\after_last($fqcn, '\\');
                    $importPath = $this->computeImportPath($namespace, $targetNamespace);
                    $importKey = "{$importPath}::{$typeName}";

                    $imports[$importKey] ??= "import type { {$typeName} } from '{$importPath}';";
                }
            }
        }

        return array_values($imports);
    }

    /**
     * @return string[]
     */
    private function collectInterfaceReferences(InterfaceDefinition $definition): array
    {
        $references = [];

        foreach ($definition->properties as $property) {
            $references = [...$references, ...$property->type->references];
        }

        return array_values(array_unique($references));
    }

    private function generateDefinition(TypeDefinition|InterfaceDefinition $definition): string
    {
        $typeName = Str\after_last($definition->class, '\\');

        if ($definition instanceof TypeDefinition) {
            return vsprintf('export type %s = %s;', [
                $typeName,
                $this->renderer->render(
                    type: $definition->type,
                    symbolRenderer: static fn (string $fqcn): string => Str\after_last($fqcn, '\\'),
                ),
            ]);
        }

        $lines = [];
        $lines[] = "export interface {$typeName} {";

        foreach ($definition->properties as $property) {
            $lines[] = vsprintf('  %s%s: %s;', [
                $property->name,
                $property->isNullable ? '?' : '',
                $this->renderer->render(
                    type: $property->type,
                    symbolRenderer: static fn (string $fqcn): string => Str\after_last($fqcn, '\\'),
                ),
            ]);
        }

        $lines[] = '}';

        return (string) Arr\implode($lines, glue: "\n");
    }

    private function namespaceToFilePath(string $namespace): string
    {
        $parts = explode('\\', $namespace);
        $kebabParts = Arr\map($parts, fn (string $part) => Str\to_kebab_case($part));
        $path = (string) Arr\implode($kebabParts, glue: '/');

        return $this->config->directory . '/' . $path . '/index.ts';
    }

    private function computeImportPath(string $sourceNamespace, string $targetNamespace): string
    {
        $sourceParts = explode('\\', $sourceNamespace);
        $targetParts = explode('\\', $targetNamespace);

        $commonLength = 0;
        $minLength = min(count($sourceParts), count($targetParts));

        for ($i = 0; $i < $minLength; $i++) {
            if ($sourceParts[$i] !== $targetParts[$i]) {
                break;
            }

            $commonLength++;
        }

        $upLevels = count($sourceParts) - $commonLength;
        $targetDiff = array_slice($targetParts, $commonLength);
        $targetKebab = Arr\map($targetDiff, fn (string $part) => Str\to_kebab_case($part));

        if ($upLevels === 0 && $targetKebab === []) {
            return './';
        }

        $upPath = $upLevels > 0 ? str_repeat('../', $upLevels) : './';
        $downPath = $targetKebab !== [] ? (string) Arr\implode($targetKebab, glue: '/') : '';

        return rtrim($upPath . $downPath, '/');
    }
}
