<?php

declare(strict_types=1);

namespace Tempest\Generation\Tests\TypeScript\Writers;

use PHPUnit\Framework\Attributes\PostCondition;
use PHPUnit\Framework\Attributes\PreCondition;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Tempest\Generation\TypeScript\InterfaceDefinition;
use Tempest\Generation\TypeScript\PropertyDefinition;
use Tempest\Generation\TypeScript\TypeDefinition;
use Tempest\Generation\TypeScript\TypeNodes\LiteralTypeNode;
use Tempest\Generation\TypeScript\TypeNodes\PrimitiveTypeNode;
use Tempest\Generation\TypeScript\TypeNodes\SymbolTypeNode;
use Tempest\Generation\TypeScript\TypeNodes\UnionTypeNode;
use Tempest\Generation\TypeScript\TypeScriptOutput;
use Tempest\Generation\TypeScript\Writers\DirectoryTypeScriptGenerationConfig;
use Tempest\Generation\TypeScript\Writers\DirectoryWriter;
use Tempest\Reflection\TypeReflector;
use Tempest\Support\Filesystem;

final class DirectoryWriterTest extends TestCase
{
    private string $directory;

    #[PreCondition]
    protected function configure(): void
    {
        $this->directory = sys_get_temp_dir() . '/tempest_typescript_directory_' . uniqid();

        Filesystem\ensure_directory_exists($this->directory);
    }

    #[PostCondition]
    protected function cleanup(): void
    {
        Filesystem\delete($this->directory);
    }

    #[Test]
    public function writes_types_in_directories(): void
    {
        $directory = $this->directory . '/types';
        $config = new DirectoryTypeScriptGenerationConfig(directory: $directory);
        $writer = new DirectoryWriter($config);

        $userInterface = new InterfaceDefinition(
            class: 'App\\Models\\User',
            originalType: new TypeReflector('string'),
            properties: [
                new PropertyDefinition(
                    name: 'id',
                    type: new PrimitiveTypeNode('number'),
                    isNullable: true,
                ),
                new PropertyDefinition(
                    name: 'name',
                    type: new PrimitiveTypeNode('string'),
                    isNullable: false,
                ),
                new PropertyDefinition(
                    name: 'role',
                    type: new SymbolTypeNode('App\\Security\\Role'),
                    isNullable: false,
                ),
            ],
        );

        $postType = new TypeDefinition(
            class: 'App\\Models\\Post',
            originalType: new TypeReflector('string'),
            type: new PrimitiveTypeNode('string'),
            isNullable: false,
        );

        $roleInterface = new InterfaceDefinition(
            class: 'App\\Security\\Role',
            originalType: new TypeReflector('string'),
            properties: [
                new PropertyDefinition(
                    name: 'name',
                    type: new PrimitiveTypeNode('string'),
                    isNullable: false,
                ),
            ],
        );

        $themeEnum = new TypeDefinition(
            class: 'App\\Models\\Theme',
            originalType: new TypeReflector('string'),
            type: new UnionTypeNode([
                new LiteralTypeNode('dark'),
                new LiteralTypeNode('light'),
            ]),
            isNullable: false,
        );

        $output = new TypeScriptOutput(
            namespaces: [
                'App\\Models' => [$userInterface, $postType, $themeEnum],
                'App\\Security' => [$roleInterface],
            ],
        );

        $writer->write($output);

        $this->assertFileExists($directory . '/app/models/index.ts');
        $this->assertFileExists($directory . '/app/security/index.ts');

        $models = Filesystem\read_file($directory . '/app/models/index.ts');

        $this->assertStringContainsString('This file contains TypeScript definitions generated by Tempest', $models);
        $this->assertStringContainsString("import type { Role } from '../security';", $models);
        $this->assertStringContainsString('export interface User {', $models);
        $this->assertStringContainsString('id?: number;', $models);
        $this->assertStringContainsString('name: string;', $models);
        $this->assertStringContainsString('role: Role;', $models);
        $this->assertStringContainsString('export type Post = string;', $models);
        $this->assertStringContainsString("export type Theme = 'dark' | 'light';", $models);

        $security = Filesystem\read_file($directory . '/app/security/index.ts');

        $this->assertStringContainsString('export interface Role {', $security);
        $this->assertStringContainsString('name: string;', $security);
        $this->assertStringNotContainsString('import', $security);
    }
}
