name: Feature request
description: Tempest is a work in progress! Let us know about a feature you would like to see in the framework.
labels: ['Triage']
type: 'Feature'
body:
- type: textarea
  attributes:
    label: Description
    description: Please provide a detailed description of the feature you would like to see added.
  validations:
    required: true
- type: textarea
  attributes:
    label: Benefits
    description: Please provide some thoughts on how this feature may benefit others using the framework.
  validations:
    required: true
