name: "Sub-split packages"

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  get_packages:
    name: Get packages
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          coverage: none

      - uses: actions/checkout@v4

      - name: Get packages
        id: get_json
        run: echo "matrix=$(bin/get-packages) >> $GITHUB_OUTPUT"

      - name: Output packages
        run: echo "${{ steps.get_json.outputs.json }}"

  packages_split:
    name: Split package ${{ matrix.package.name }}
    needs: get_packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.get_packages.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
          pip-install: git-filter-repo

      - name: Split Package
        run:
          ./bin/split "${{ matrix.package.name }}"
